### ISSUE TITLE
Mqtt

### ISSUE THREAD

**Issue by r34220** [DutchDevelop/BambulabLedController#3]
Do you know if something changed with the mqtt info? I have compiled and flashed toba d1 mini but it appears I am getting the messages from the printer watching athe serial output from the Arduino IDE but I only see data that turns off the led strip. I have verified my circuit to drive the led strip works when a test sketch.

**Comment by DutchDevelop** [comment]
No nothing changed? What is your printer?

**Comment by r34220** [comment]
X1 Carbon

**Comment by DutchDevelop** [comment]
Then it should just work fine

**Comment by r34220** [comment]
Okay, thanks.
